### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by zkochan** [bendrucker/major-versions#1]
When running `npm test`, this error happens: `TypeError: Invalid Version: 2.0.0`.

Seems to be happening since `is-comparator-valid@1.0.1` has been published

**Comment by bendrucker** [comment]
Thanks, because of this every both packages effectively need to resolve to the same version of semver:

https://github.com/npm/node-semver/blob/master/semver.js#L237

**Comment by zkochan** [comment]
Thanks for the quick fix!
